# Declares an action that triggers Google Cloud Infrastructure Manager tasks on changes in the foundations/ directory.
# The intent is to trigger a Terraform plan on PR creation and changes, and an apply on merge to main.
#
# yamllint disable rule:line-length
---
name: 'Infra Manager: Foundations'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      action:
        description: Infrastructure Manager action to trigger
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - delete
          - output
  pull_request:
    paths:
      - 'foundations/**'
      - .github/workflows/infra-manager-foundations.yml
      - .github/workflows/infra-manager-wrapper.sh
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - 'foundations/**'
      - .github/workflows/infra-manager-foundations.yml
      - .github/workflows/infra-manager-wrapper.sh

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TFPLANDOC_VERSION: 0.4.1
  # These values define the properties used by Infrastructure Manager
  # NOTE: DEPLOYMENT_ID must be less than 40 chars or Infra Manager will throw an error
  DEPLOYMENT_ID: example-deployment
  DEPLOYMENT_PROJECT_ID: ${{ vars.PROJECT_ID }}
  DEPLOYMENT_REGION: us-west1
  DEPLOYMENT_TF_VERSION: "1.5.7"
  DEPLOYMENT_SERVICE_ACCOUNT_NAME: "projects/${{ vars.PROJECT_ID }}/serviceAccounts/${{ secrets.IAC_SERVICE_ACCOUNT }}"
  DEPLOYMENT_LABELS: "owner=emes,email=m_dot_emes_at_f5_dot_com"
jobs:
  infra-manager:
    runs-on: ubuntu-latest
    # TODO: Modify environment as needed above and enable in real project that uses infrastructure manager
    if: false
    env:
      DEPLOYMENT_GIT_URL: "${{ github.server_url }}/${{ github.repository }}"
      DEPLOYMENT_GIT_SHA: "${{ github.sha }}"
      DEPLOYMENT_GIT_REF: "${{ github.head_ref || github.ref_name }}"
      DEPLOYMENT_GIT_SOURCE_DIRECTORY: foundations
      DEPLOYMENT_INPUTS_FILE: "${{ github.sha }}.tfvars"
    steps:
      - name: Checkout source
        id: checkout
        uses: actions/checkout@v6
      - name: Google Authentication
        id: google-auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
      - name: Google Cloud CLI
        id: gcloud-cli
        uses: google-github-actions/setup-gcloud@v3
      - name: Get PR number
        id: get_pr_number
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            if (context.issue.number) {
              return context.issue.number;
            } else {
              data = (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data;
              return data.length > 0 ? data[0].number : undefined;
            }
      - name: Get Infra Manager action steps
        id: get_im_action_steps
        uses: actions/github-script@v8
        env:
          EXPLICIT_ACTION: ${{ case(github.event_name == 'workflow_dispatch', inputs.action || 'plan', '') }}
        with:
          script: |
            const explicitAction = process.env.EXPLICIT_ACTION;
            const exec_plan = explicitAction == 'plan' || context.eventName == 'pull_request';
            const exec_apply = explicitAction == 'apply' || context.eventName == 'push';
            const exec_delete = explicitAction == 'delete';
            const exec_output = explicitAction == 'output' || exec_apply;
            core.setOutput('exec_plan', exec_plan);
            core.setOutput('exec_apply', exec_apply);
            core.setOutput('exec_delete', exec_delete);
            core.setOutput('exec_output', exec_output);
      - name: Install Terraform binary
        id: install-terraform
        uses: hashicorp/setup-terraform@v4
        if: ${{ fromJson(steps.get_im_action_steps.outputs.exec_output) }}
        with:
          terraform_version: "${{ env.DEPLOYMENT_TF_VERSION}}"
      - name: Install tfplandoc
        id: install-tfplandoc
        if: ${{ fromJson(steps.get_im_action_steps.outputs.exec_plan) }}
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: Azure/tfplandoc
          tag: v${{ env.TFPLANDOC_VERSION }}
      - name: Create local terraform variables file
        id: create-tf-vars-file
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_plan) || fromJson(steps.get_im_action_steps.outputs.exec_apply) }}
        # NOTE: This file defines the inputs for the Terraform executed by Infrastructure Manager. It mostly consists
        # of substitutions from root and job environment, but other values can be added too (e.g. labels), or can be
        # removed if not used (e.g. NGINX JWT secret identifier).
        # NOTE 2: An alternative is to disable/remove this step and rely on `terraform.tfvars` or `*.auto.tfvars` that
        # has been committed to the repo.
        run: |
          cat <<'EOF' > ${{ env.DEPLOYMENT_INPUTS_FILE }}
          # Autogenerated by ${{ github.workflow }} workflow
          project_id                   = "${{ env.DEPLOYMENT_PROJECT_ID }}"
          name                         = "${{ env.DEPLOYMENT_ID }}"
          region                       = "${{ env.DEPLOYMENT_REGION }}"
          repository                   = "${{ vars.OCI_REGISTRY }}"
          cloud_deploy_service_account = "${{ secrets.DEPLOY_SERVICE_ACCOUNT }}"
          nginx_jwt_secret_id          = "${{ vars.NGINX_JWT_SECRET }}"
          labels                       = {
            owner = "emes"
            email = "m_dot_emes_at_f5_dot_com"
          }
          EOF
      - name: Generate preview plan
        id: generate-tf-plan
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_plan) }}
        run: ./.github/workflows/infra-manager-wrapper.sh plan
      - name: Generate markdown summary of plan for PR
        id: generate-md-from-plan
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_plan) }}
        run: |
          tfplandoc_v${{ env.TFPLANDOC_VERSION }} generate "${{ github.sha }}.json" > "${{ github.sha }}.plan.md"
      - name: Echo markdown plan summary to stdout if not associated with a PR
        id: cat-md-plan
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_plan) && !steps.get_pr_number.outputs.result }}
        run: |
          cat "${{ github.sha }}.plan.md"
      - name: Add markdown output as comment on PR
        id: pr-md-plan
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_plan) && steps.get_pr_number.outputs.result }}
        uses: actions/github-script@v8
        env:
          ISSUE_NUMBER: ${{ steps.get_pr_number.outputs.result }}
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ github.sha }}.plan.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: process.env.ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Proposed Changes\n\nInfrastructure Manager will make the following changes on merge to main, or on manual apply.\n\n' + plan,
            })
      - name: Apply changes
        id: apply-tf
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_apply) }}
        run: ./.github/workflows/infra-manager-wrapper.sh apply
      - name: Generate a markdown output summary
        id: generate-tf-output
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_output) }}
        run: ./.github/workflows/infra-manager-wrapper.sh output
      - name: Echo output summary to stdout if not associated with a PR
        id: cat-tf-output
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_output) && !steps.get_pr_number.outputs.result }}
        run: |
          cat "${{ github.sha }}.output.json"
      - name: Add markdown output as comment on PR
        id: pr-tf-output
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_output) && steps.get_pr_number.outputs.result }}
        uses: actions/github-script@v8
        env:
          ISSUE_NUMBER: ${{ steps.get_pr_number.outputs.result }}
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('${{ github.sha }}.output.hcl', 'utf8');
            github.rest.issues.createComment({
              issue_number: process.env.ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Output values\n\n```hcl\n' + output + '\n```\n',
            })
      - name: Delete deployment
        id: delete-tf
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.exec_delete) }}
        run: ./.github/workflows/infra-manager-wrapper.sh delete
