---
name: infra-manager

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      action:
        description: Infrastructure Manager action to trigger
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - delete
  pull_request:
    paths:
      - 'foundations/**'
      - scripts/infra-manager-wrapper.sh
  push:
    branches:
      - main
    paths:
      - 'foundations/**'
      - scripts/infra-manager-wrapper.sh

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TFPLANDOC_VERSION: 0.4.1
  # These values define the properties used by Infrastructure Manager
  DEPLOYMENT_ID: example-deployment
  DEPLOYMENT_PROJECT_ID: ${{ vars.PROJECT_ID }}
  DEPLOYMENT_REGION: us-west1
  DEPLOYMENT_TF_VERSION: "1.5.7"
  DEPLOYMENT_SERVICE_ACCOUNT_NAME: "projects/${{ vars.PROJECT_ID }}/serviceAccounts/${{ secrets.IAC_SERVICE_ACCOUNT }}"

jobs:
  infra-manager:
    runs-on: ubuntu-latest
    # TODO: Modify environment as needed above and enable in real project that uses infrastructure manager
    if: false
    env:
      DEPLOYMENT_GIT_URL: "${{ github.server_url }}/${{ github.repository }}"
      DEPLOYMENT_GIT_SHA: "${{ github.sha }}"
      DEPLOYMENT_GIT_REF: "${{ github.head_ref || github.ref_name }}"
      DEPLOYMENT_GIT_SOURCE_DIRECTORY: foundations
      DEPLOYMENT_INPUTS_FILE: "${{ github.sha }}.tfvars"
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ env.DEPLOYMENT_TF_VERSION}}"
      - name: Create local terraform variables file
        # NOTE: This file defines the inputs for the Terraform executed by Infrastructure Manager. It mostly consists
        # of substitutions from root and job environment, but other values can be added too (e.g. labels), or can be
        # removed if not used (e.g. NGINX JWT secret identifier).
        run: |
          cat <<'EOF' > ${{ env.DEPLOYMENT_INPUTS_FILE }}
          # Autogenerated by ${{ github.workflow }} workflow
          project_id                   = "${{ env.DEPLOYMENT_PROJECT_ID }}"
          name                         = "${{ env.DEPLOYMENT_ID }}"
          region                       = "${{ env.DEPLOYMENT_REGION }}"
          repository                   = "${{ vars.OCI_REGISTRY }}"
          cloud_deploy_service_account = "${{ secrets.DEPLOY_SERVICE_ACCOUNT }}"
          nginx_jwt_secret_id          = "${{ vars.NGINX_JWT_SECRET }}"
          labels                       = {}
          EOF
      - name: Generate preview plan
        if: ${{ success() && (inputs.action || 'apply') == 'apply' }}
        run: ./.github/workflows/infra-manager-wrapper.sh plan
      - name: Generate markdown summary of plan for PR
        if: ${{ success() && (inputs.action || 'apply') == 'apply' && github.event.number }}
        # yamllint disable rule:line-length
        run: |
          curl -fsSLO https://github.com/Azure/tfplandoc/releases/download/v${{ env.TFPLANDOC_VERSION }}/tfplandoc_${{ env.TFPLANDOC_VERSION }}_linux_amd64.zip
          unzip tfplandoc_${{ env.TFPLANDOC_VERSION }}_linux_amd64.zip tfplandoc_v${{ env.TFPLANDOC_VERSION }}
          ./tfplandoc_v${{ env.TFPLANDOC_VERSION }} generate "${{ github.sha }}.json" > "${{ github.sha }}.md"
        # yamllint enable rule:line-length
      - name: Add markdown output as comment in PR
        if: ${{ success() && (inputs.action || 'apply') == 'apply' && github.event.number }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ github.sha }}.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Proposed Changes\n\nInfrastructure Manager will make the following changes\n\n' + plan
            })
      - name: Apply changes
        if: ${{ success() && (inputs.action || 'apply') == 'apply' }}
        run: ./.github/workflows/infra-manager-wrapper.sh apply
      - name: Add applied comment to PR
        if: ${{ success() && (inputs.action || 'apply') == 'apply' && github.event.number }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Changes applied\n\nThe changes have been successfully applied by Infrastructure Manager'
            })
      - name: Delete deployment
        if: ${{ success() && (inputs.action || 'apply') == 'delete' }}
        run: ./.github/workflows/infra-manager-wrapper.sh delete
